export const sampleDataset = {
  text: [
    { id: "T1", content: "You did an amazing job today!", category: "positive", negativity_score: 5, level: 1 },
    { id: "T2", content: "Thank you for your help.", category: "positive", negativity_score: 3, level: 1 },
    { id: "T3", content: "I appreciate your effort.", category: "positive", negativity_score: 4, level: 1 },
    { id: "T4", content: "This looks great!", category: "positive", negativity_score: 2, level: 1 },
    { id: "T5", content: "Let's work together and improve this.", category: "positive", negativity_score: 5, level: 1 },
    { id: "T6", content: "I am not very happy with this service.", category: "complaint", negativity_score: 25, level: 2 },
    { id: "T7", content: "This could be better.", category: "complaint", negativity_score: 22, level: 2 },
    { id: "T8", content: "I expected more from this product.", category: "complaint", negativity_score: 30, level: 2 },
    { id: "T9", content: "This is disappointing.", category: "complaint", negativity_score: 28, level: 2 },
    { id: "T10", content: "I am frustrated with the delay.", category: "complaint", negativity_score: 35, level: 2 },
    { id: "T11", content: "You are really annoying.", category: "harassment", negativity_score: 50, level: 3 },
    { id: "T12", content: "This is such a stupid idea.", category: "harassment", negativity_score: 55, level: 3 },
    { id: "T13", content: "You clearly don't know what you're doing.", category: "harassment", negativity_score: 52, level: 3 },
    { id: "T14", content: "Stop being so useless.", category: "harassment", negativity_score: 58, level: 3 },
    { id: "T15", content: "This is garbage.", category: "harassment", negativity_score: 60, level: 3 },
    { id: "T16", content: "I hate you.", category: "abuse", negativity_score: 65, level: 4 },
    { id: "T17", content: "You are completely worthless.", category: "abuse", negativity_score: 68, level: 4 },
    { id: "T18", content: "Shut up and disappear.", category: "abuse", negativity_score: 70, level: 4 },
    { id: "T19", content: "I can't stand you.", category: "abuse", negativity_score: 67, level: 4 },
    { id: "T20", content: "Everything about this is terrible.", category: "abuse", negativity_score: 69, level: 4 },
    { id: "T21", content: "I will hurt you.", category: "threat", negativity_score: 85, level: 5 },
    { id: "T22", content: "You deserve to suffer.", category: "threat", negativity_score: 90, level: 5 },
    { id: "T23", content: "I will destroy you.", category: "threat", negativity_score: 88, level: 5 },
    { id: "T24", content: "You should be eliminated.", category: "threat", negativity_score: 92, level: 5 },
    { id: "T25", content: "I hope something bad happens to you.", category: "threat", negativity_score: 80, level: 5 },
  ],
  image: [
    { id: "I1", content: "Smiling group photo", category: "positive", negativity_score: 5, level: 1 },
    { id: "I2", content: "Friendly handshake at an office meeting", category: "positive", negativity_score: 4, level: 1 },
    { id: "I3", content: "A person looking upset and frustrated", category: "complaint", negativity_score: 28, level: 2 },
    { id: "I4", content: "Graffiti with mild offensive language", category: "harassment", negativity_score: 52, level: 3 },
    { id: "I5", content: "Angry face with offensive gesture", category: "harassment", negativity_score: 60, level: 3 },
    { id: "I6", content: "Person pointing aggressively at camera", category: "abuse", negativity_score: 67, level: 4 },
    { id: "I7", content: "Threatening stance with weapon visible", category: "threat", negativity_score: 85, level: 5 },
    { id: "I8", content: "Explicit violent imagery", category: "threat", negativity_score: 92, level: 5 },
  ],
  audio: [
    { id: "A1", content: "Thank you for helping me.", category: "positive", negativity_score: 5, level: 1 },
    { id: "A2", content: "I appreciate what you did for me.", category: "positive", negativity_score: 4, level: 1 },
    { id: "A3", content: "I'm a bit unhappy with the result.", category: "complaint", negativity_score: 27, level: 2 },
    { id: "A4", content: "This is not what I expected at all.", category: "complaint", negativity_score: 33, level: 2 },
    { id: "A5", content: "You are so annoying.", category: "harassment", negativity_score: 55, level: 3 },
    { id: "A6", content: "Stop talking to me like that.", category: "harassment", negativity_score: 58, level: 3 },
    { id: "A7", content: "I can't believe how terrible you are.", category: "abuse", negativity_score: 68, level: 4 },
    { id: "A8", content: "I will make you regret this.", category: "threat", negativity_score: 90, level: 5 },
    { id: "A9", content: "You will pay for what you did.", category: "threat", negativity_score: 87, level: 5 },
  ],
};
